import type { ComponentType } from "react";
import {
  Zap,
  Clock,
  Network,
  AlertTriangle,
  Shield,
  Printer,
  Phone,
  Keyboard,
  ShieldOff,
  HardDrive,
  Cpu,
  Moon,
  FileText,
  Users,
  Fingerprint,
  Radio,
  MonitorOff,
  Activity,
  Music,
  Home,
  Server,
  Eye,
  Mic,
  Newspaper,
  Layout,
  MessageSquare,
  Globe,
  Chrome,
  Monitor,
  Code,
  Pen,
  Clipboard,
  SpellCheck,
  Gamepad2,
  X,
  Gamepad,
  Wifi,
  Terminal,
  BookOpen,
  Calendar,
  Cloud,
  Download,
} from "lucide-react";

export type OptimizerCategory = "system" | "disk" | "privacy" | "apps" | "touch" | "gaming";

export interface OptimizerItem {
  id: string;
  stateKey: string;
  category: OptimizerCategory;
  icon: ComponentType<{ size?: number; strokeWidth?: number }>;
  color: string;
  enableCmd: string;
  disableCmd: string;
  titleKey: string;
  descKey: string;
  requiresReboot: boolean;
}

// 预定义颜色池（固定顺序，避免刷新变化）
const COLORS = [
  "#FF6B9D", "#3182CE", "#38A169", "#DD6B20", "#805AD5",
  "#E53E3E", "#00B5D8", "#D69E2E", "#319795", "#667EEA",
  "#ED64A6", "#F56565", "#48BB78", "#9F7AEA", "#F6AD55",
];

export const optimizerItems: OptimizerItem[] = [
  // ============== 系统 ==============
  {
    id: "performanceTweaks",
    stateKey: "master",
    category: "system",
    icon: Zap,
    color: COLORS[0],
    enableCmd: "enable_performance_tweaks",
    disableCmd: "disable_performance_tweaks",
    titleKey: "systemOptimizer.system.performanceTweaks",
    descKey: "systemOptimizer.system.performanceTweaksDesc",
    requiresReboot: false,
  },
  {
    id: "removeMenuDelay",
    stateKey: "removeMenuDelay",
    category: "system",
    icon: Clock,
    color: COLORS[1],
    enableCmd: "remove_menu_delay",
    disableCmd: "restore_menu_delay",
    titleKey: "systemOptimizer.system.removeMenuDelay",
    descKey: "systemOptimizer.system.removeMenuDelayDesc",
    requiresReboot: false,
  },
  {
    id: "disableNetworkThrottling",
    stateKey: "disableNetworkThrottling",
    category: "system",
    icon: Network,
    color: COLORS[2],
    enableCmd: "disable_network_throttling",
    disableCmd: "enable_network_throttling",
    titleKey: "systemOptimizer.system.disableNetworkThrottling",
    descKey: "systemOptimizer.system.disableNetworkThrottlingDesc",
    requiresReboot: false,
  },
  {
    id: "disableErrorReporting",
    stateKey: "disableErrorReporting",
    category: "system",
    icon: AlertTriangle,
    color: COLORS[3],
    enableCmd: "disable_error_reporting",
    disableCmd: "enable_error_reporting",
    titleKey: "systemOptimizer.system.disableErrorReporting",
    descKey: "systemOptimizer.system.disableErrorReportingDesc",
    requiresReboot: false,
  },
  {
    id: "disableCompatibilityAssistant",
    stateKey: "disableCompatibilityAssistant",
    category: "system",
    icon: Shield,
    color: COLORS[4],
    enableCmd: "disable_compatibility_assistant",
    disableCmd: "enable_compatibility_assistant",
    titleKey: "systemOptimizer.system.disableCompatibilityAssistant",
    descKey: "systemOptimizer.system.disableCompatibilityAssistantDesc",
    requiresReboot: false,
  },
  {
    id: "disablePrintService",
    stateKey: "disablePrintService",
    category: "system",
    icon: Printer,
    color: COLORS[5],
    enableCmd: "disable_print_service",
    disableCmd: "enable_print_service",
    titleKey: "systemOptimizer.system.disablePrintService",
    descKey: "systemOptimizer.system.disablePrintServiceDesc",
    requiresReboot: true,
  },
  {
    id: "disableFaxService",
    stateKey: "disableFaxService",
    category: "system",
    icon: Phone,
    color: COLORS[6],
    enableCmd: "disable_fax_service",
    disableCmd: "enable_fax_service",
    titleKey: "systemOptimizer.system.disableFaxService",
    descKey: "systemOptimizer.system.disableFaxServiceDesc",
    requiresReboot: true,
  },
  {
    id: "disableStickyKeys",
    stateKey: "disableStickyKeys",
    category: "system",
    icon: Keyboard,
    color: COLORS[7],
    enableCmd: "disable_sticky_keys",
    disableCmd: "enable_sticky_keys",
    titleKey: "systemOptimizer.system.disableStickyKeys",
    descKey: "systemOptimizer.system.disableStickyKeysDesc",
    requiresReboot: false,
  },
  {
    id: "disableSmartScreen",
    stateKey: "disableSmartScreen",
    category: "system",
    icon: ShieldOff,
    color: COLORS[8],
    enableCmd: "disable_smart_screen",
    disableCmd: "enable_smart_screen",
    titleKey: "systemOptimizer.system.disableSmartScreen",
    descKey: "systemOptimizer.system.disableSmartScreenDesc",
    requiresReboot: false,
  },

  // ============== 新增系统（ZyperWin++）==============
  {
    id: "disableCEIP",
    stateKey: "disableCEIP",
    category: "system",
    icon: Shield,
    color: COLORS[9],
    enableCmd: "disable_ceip",
    disableCmd: "enable_ceip",
    titleKey: "systemOptimizer.system.disableCEIP",
    descKey: "systemOptimizer.system.disableCEIPDesc",
    requiresReboot: false,
  },
  {
    id: "disableTrkWks",
    stateKey: "disableTrkWks",
    category: "system",
    icon: Activity,
    color: COLORS[10],
    enableCmd: "disable_trk_wks",
    disableCmd: "enable_trk_wks",
    titleKey: "systemOptimizer.system.disableTrkWks",
    descKey: "systemOptimizer.system.disableTrkWksDesc",
    requiresReboot: true,
  },
  {
    id: "disableAutoMaintenance",
    stateKey: "disableAutoMaintenance",
    category: "system",
    icon: Clock,
    color: COLORS[11],
    enableCmd: "disable_auto_maintenance",
    disableCmd: "enable_auto_maintenance",
    titleKey: "systemOptimizer.system.disableAutoMaintenance",
    descKey: "systemOptimizer.system.disableAutoMaintenanceDesc",
    requiresReboot: false,
  },
  {
    id: "enableLargeSysCache",
    stateKey: "enableLargeSysCache",
    category: "system",
    icon: Cpu,
    color: COLORS[12],
    enableCmd: "enable_large_sys_cache",
    disableCmd: "disable_large_sys_cache",
    titleKey: "systemOptimizer.system.enableLargeSysCache",
    descKey: "systemOptimizer.system.enableLargeSysCacheDesc",
    requiresReboot: true,
  },
  {
    id: "disableSpectrePatch",
    stateKey: "disableSpectrePatch",
    category: "system",
    icon: ShieldOff,
    color: COLORS[13],
    enableCmd: "disable_spectre_patch",
    disableCmd: "enable_spectre_patch",
    titleKey: "systemOptimizer.system.disableSpectrePatch",
    descKey: "systemOptimizer.system.disableSpectrePatchDesc",
    requiresReboot: true,
  },
  {
    id: "disableAutoDebug",
    stateKey: "disableAutoDebug",
    category: "system",
    icon: Monitor,
    color: COLORS[14],
    enableCmd: "disable_auto_debug",
    disableCmd: "enable_auto_debug",
    titleKey: "systemOptimizer.system.disableAutoDebug",
    descKey: "systemOptimizer.system.disableAutoDebugDesc",
    requiresReboot: false,
  },
  {
    id: "disableCrashDump",
    stateKey: "disableCrashDump",
    category: "system",
    icon: HardDrive,
    color: COLORS[0],
    enableCmd: "disable_crash_dump",
    disableCmd: "enable_crash_dump",
    titleKey: "systemOptimizer.system.disableCrashDump",
    descKey: "systemOptimizer.system.disableCrashDumpDesc",
    requiresReboot: false,
  },
  {
    id: "disableAuditLog",
    stateKey: "disableAuditLog",
    category: "system",
    icon: Users,
    color: COLORS[1],
    enableCmd: "disable_audit_log",
    disableCmd: "enable_audit_log",
    titleKey: "systemOptimizer.system.disableAuditLog",
    descKey: "systemOptimizer.system.disableAuditLogDesc",
    requiresReboot: false,
  },
  {
    id: "disableWfpDiag",
    stateKey: "disableWfpDiag",
    category: "system",
    icon: Radio,
    color: COLORS[2],
    enableCmd: "disable_wfp_diag",
    disableCmd: "enable_wfp_diag",
    titleKey: "systemOptimizer.system.disableWfpDiag",
    descKey: "systemOptimizer.system.disableWfpDiagDesc",
    requiresReboot: false,
  },

  // ============== 磁盘 ==============
  {
    id: "disableSystemRestore",
    stateKey: "disableSystemRestore",
    category: "disk",
    icon: HardDrive,
    color: COLORS[9],
    enableCmd: "disable_system_restore",
    disableCmd: "enable_system_restore",
    titleKey: "systemOptimizer.disk.disableSystemRestore",
    descKey: "systemOptimizer.disk.disableSystemRestoreDesc",
    requiresReboot: false,
  },
  {
    id: "disableSuperfetch",
    stateKey: "disableSuperfetch",
    category: "disk",
    icon: Cpu,
    color: COLORS[10],
    enableCmd: "disable_superfetch",
    disableCmd: "enable_superfetch",
    titleKey: "systemOptimizer.disk.disableSuperfetch",
    descKey: "systemOptimizer.disk.disableSuperfetchDesc",
    requiresReboot: true,
  },
  {
    id: "disableHibernate",
    stateKey: "disableHibernate",
    category: "disk",
    icon: Moon,
    color: COLORS[11],
    enableCmd: "disable_hibernate",
    disableCmd: "enable_hibernate",
    titleKey: "systemOptimizer.disk.disableHibernate",
    descKey: "systemOptimizer.disk.disableHibernateDesc",
    requiresReboot: false,
  },
  {
    id: "disableNtfsTimestamp",
    stateKey: "disableNtfsTimestamp",
    category: "disk",
    icon: FileText,
    color: COLORS[12],
    enableCmd: "disable_ntfs_timestamp",
    disableCmd: "enable_ntfs_timestamp",
    titleKey: "systemOptimizer.disk.disableNtfsTimestamp",
    descKey: "systemOptimizer.disk.disableNtfsTimestampDesc",
    requiresReboot: true,
  },
  {
    id: "disableMyPeople",
    stateKey: "disableMyPeople",
    category: "disk",
    icon: Users,
    color: COLORS[13],
    enableCmd: "disable_my_people",
    disableCmd: "enable_my_people",
    titleKey: "systemOptimizer.disk.disableMyPeople",
    descKey: "systemOptimizer.disk.disableMyPeopleDesc",
    requiresReboot: false,
  },
  {
    id: "disableTPMCheck",
    stateKey: "disableTPMCheck",
    category: "disk",
    icon: Fingerprint,
    color: COLORS[14],
    enableCmd: "disable_tpm_check",
    disableCmd: "enable_tpm_check",
    titleKey: "systemOptimizer.disk.disableTPMCheck",
    descKey: "systemOptimizer.disk.disableTPMCheckDesc",
    requiresReboot: true,
  },
  {
    id: "disableSensorServices",
    stateKey: "disableSensorServices",
    category: "disk",
    icon: Radio,
    color: COLORS[1],
    enableCmd: "disable_sensor_services",
    disableCmd: "enable_sensor_services",
    titleKey: "systemOptimizer.disk.disableSensorServices",
    descKey: "systemOptimizer.disk.disableSensorServicesDesc",
    requiresReboot: true,
  },
  {
    id: "removeCastToDevice",
    stateKey: "removeCastToDevice",
    category: "disk",
    icon: MonitorOff,
    color: COLORS[2],
    enableCmd: "remove_cast_to_device",
    disableCmd: "add_cast_to_device",
    titleKey: "systemOptimizer.disk.removeCastToDevice",
    descKey: "systemOptimizer.disk.removeCastToDeviceDesc",
    requiresReboot: true,
  },

  // ============== 隐私 ==============
  {
    id: "disableTelemetryTasks",
    stateKey: "disableTelemetryTasks",
    category: "privacy",
    icon: Activity,
    color: COLORS[3],
    enableCmd: "disable_telemetry_tasks",
    disableCmd: "enable_telemetry_tasks",
    titleKey: "systemOptimizer.privacy.disableTelemetryTasks",
    descKey: "systemOptimizer.privacy.disableTelemetryTasksDesc",
    requiresReboot: false,
  },
  {
    id: "disableMediaPlayerSharing",
    stateKey: "disableMediaPlayerSharing",
    category: "privacy",
    icon: Music,
    color: COLORS[4],
    enableCmd: "disable_media_player_sharing",
    disableCmd: "enable_media_player_sharing",
    titleKey: "systemOptimizer.privacy.disableMediaPlayerSharing",
    descKey: "systemOptimizer.privacy.disableMediaPlayerSharingDesc",
    requiresReboot: true,
  },
  {
    id: "disableHomeGroup",
    stateKey: "disableHomeGroup",
    category: "privacy",
    icon: Home,
    color: COLORS[5],
    enableCmd: "disable_home_group",
    disableCmd: "enable_home_group",
    titleKey: "systemOptimizer.privacy.disableHomeGroup",
    descKey: "systemOptimizer.privacy.disableHomeGroupDesc",
    requiresReboot: true,
  },
  {
    id: "disableSmb1",
    stateKey: "disableSmb1",
    category: "privacy",
    icon: Server,
    color: COLORS[6],
    enableCmd: "disable_smb1",
    disableCmd: "enable_smb1",
    titleKey: "systemOptimizer.privacy.disableSmb1",
    descKey: "systemOptimizer.privacy.disableSmb1Desc",
    requiresReboot: true,
  },
  {
    id: "disableSmb2",
    stateKey: "disableSmb2",
    category: "privacy",
    icon: Server,
    color: COLORS[7],
    enableCmd: "disable_smb2",
    disableCmd: "enable_smb2",
    titleKey: "systemOptimizer.privacy.disableSmb2",
    descKey: "systemOptimizer.privacy.disableSmb2Desc",
    requiresReboot: true,
  },
  {
    id: "disableTelemetryServices",
    stateKey: "disableTelemetryServices",
    category: "privacy",
    icon: Eye,
    color: COLORS[8],
    enableCmd: "disable_telemetry_services",
    disableCmd: "enable_telemetry_services",
    titleKey: "systemOptimizer.privacy.disableTelemetryServices",
    descKey: "systemOptimizer.privacy.disableTelemetryServicesDesc",
    requiresReboot: true,
  },
  {
    id: "disableCortana",
    stateKey: "disableCortana",
    category: "privacy",
    icon: Mic,
    color: COLORS[9],
    enableCmd: "disable_cortana",
    disableCmd: "enable_cortana",
    titleKey: "systemOptimizer.privacy.disableCortana",
    descKey: "systemOptimizer.privacy.disableCortanaDesc",
    requiresReboot: true,
  },
  {
    id: "disableNewsInterests",
    stateKey: "disableNewsInterests",
    category: "privacy",
    icon: Newspaper,
    color: COLORS[10],
    enableCmd: "disable_news_interests",
    disableCmd: "enable_news_interests",
    titleKey: "systemOptimizer.privacy.disableNewsInterests",
    descKey: "systemOptimizer.privacy.disableNewsInterestsDesc",
    requiresReboot: false,
  },
  {
    id: "disableStartMenuAds",
    stateKey: "disableStartMenuAds",
    category: "privacy",
    icon: Layout,
    color: COLORS[11],
    enableCmd: "disable_start_menu_ads",
    disableCmd: "enable_start_menu_ads",
    titleKey: "systemOptimizer.privacy.disableStartMenuAds",
    descKey: "systemOptimizer.privacy.disableStartMenuAdsDesc",
    requiresReboot: false,
  },
  {
    id: "disableEdgeTelemetry",
    stateKey: "disableEdgeTelemetry",
    category: "privacy",
    icon: Globe,
    color: COLORS[12],
    enableCmd: "disable_edge_telemetry",
    disableCmd: "enable_edge_telemetry",
    titleKey: "systemOptimizer.privacy.disableEdgeTelemetry",
    descKey: "systemOptimizer.privacy.disableEdgeTelemetryDesc",
    requiresReboot: false,
  },
  {
    id: "disableEdgeDiscoverBar",
    stateKey: "disableEdgeDiscoverBar",
    category: "privacy",
    icon: MessageSquare,
    color: COLORS[13],
    enableCmd: "disable_edge_discover_bar",
    disableCmd: "enable_edge_discover_bar",
    titleKey: "systemOptimizer.privacy.disableEdgeDiscoverBar",
    descKey: "systemOptimizer.privacy.disableEdgeDiscoverBarDesc",
    requiresReboot: false,
  },

  // ============== 隐私（ZyperWin++）==============
  {
    id: "disableDocumentsAccess",
    stateKey: "disableDocumentsAccess",
    category: "privacy",
    icon: FileText,
    color: COLORS[0],
    enableCmd: "disable_documents_access",
    disableCmd: "enable_documents_access",
    titleKey: "systemOptimizer.privacy.disableDocumentsAccess",
    descKey: "systemOptimizer.privacy.disableDocumentsAccessDesc",
    requiresReboot: false,
  },
  {
    id: "disableCalendarAccess",
    stateKey: "disableCalendarAccess",
    category: "privacy",
    icon: Calendar,
    color: COLORS[1],
    enableCmd: "disable_calendar_access",
    disableCmd: "enable_calendar_access",
    titleKey: "systemOptimizer.privacy.disableCalendarAccess",
    descKey: "systemOptimizer.privacy.disableCalendarAccessDesc",
    requiresReboot: false,
  },
  {
    id: "disableContactsAccess",
    stateKey: "disableContactsAccess",
    category: "privacy",
    icon: BookOpen,
    color: COLORS[2],
    enableCmd: "disable_contacts_access",
    disableCmd: "enable_contacts_access",
    titleKey: "systemOptimizer.privacy.disableContactsAccess",
    descKey: "systemOptimizer.privacy.disableContactsAccessDesc",
    requiresReboot: false,
  },
  {
    id: "disableWelcomeExperience",
    stateKey: "disableWelcomeExperience",
    category: "privacy",
    icon: MonitorOff,
    color: COLORS[3],
    enableCmd: "disable_welcome_experience",
    disableCmd: "enable_welcome_experience",
    titleKey: "systemOptimizer.privacy.disableWelcomeExperience",
    descKey: "systemOptimizer.privacy.disableWelcomeExperienceDesc",
    requiresReboot: false,
  },
  {
    id: "disableFeedbackFrequency",
    stateKey: "disableFeedbackFrequency",
    category: "privacy",
    icon: AlertTriangle,
    color: COLORS[4],
    enableCmd: "disable_feedback_frequency",
    disableCmd: "enable_feedback_frequency",
    titleKey: "systemOptimizer.privacy.disableFeedbackFrequency",
    descKey: "systemOptimizer.privacy.disableFeedbackFrequencyDesc",
    requiresReboot: false,
  },
  {
    id: "disableWritingHabits",
    stateKey: "disableWritingHabits",
    category: "privacy",
    icon: Pen,
    color: COLORS[5],
    enableCmd: "disable_writing_habits",
    disableCmd: "enable_writing_habits",
    titleKey: "systemOptimizer.privacy.disableWritingHabits",
    descKey: "systemOptimizer.privacy.disableWritingHabitsDesc",
    requiresReboot: false,
  },
  {
    id: "disableAddressBookCollect",
    stateKey: "disableAddressBookCollect",
    category: "privacy",
    icon: BookOpen,
    color: COLORS[6],
    enableCmd: "disable_address_book_collect",
    disableCmd: "enable_address_book_collect",
    titleKey: "systemOptimizer.privacy.disableAddressBookCollect",
    descKey: "systemOptimizer.privacy.disableAddressBookCollectDesc",
    requiresReboot: false,
  },
  {
    id: "disableTypingCollection",
    stateKey: "disableTypingCollection",
    category: "privacy",
    icon: Keyboard,
    color: COLORS[7],
    enableCmd: "disable_typing_collection",
    disableCmd: "enable_typing_collection",
    titleKey: "systemOptimizer.privacy.disableTypingCollection",
    descKey: "systemOptimizer.privacy.disableTypingCollectionDesc",
    requiresReboot: false,
  },
  {
    id: "disableSilentAppInstall",
    stateKey: "disableSilentAppInstall",
    category: "privacy",
    icon: Layout,
    color: COLORS[8],
    enableCmd: "disable_silent_app_install",
    disableCmd: "enable_silent_app_install",
    titleKey: "systemOptimizer.privacy.disableSilentAppInstall",
    descKey: "systemOptimizer.privacy.disableSilentAppInstallDesc",
    requiresReboot: false,
  },
  {
    id: "disableWiFiHotspots",
    stateKey: "disableWiFiHotspots",
    category: "privacy",
    icon: Wifi,
    color: COLORS[9],
    enableCmd: "disable_wifi_hotspots",
    disableCmd: "enable_wifi_hotspots",
    titleKey: "systemOptimizer.privacy.disableWiFiHotspots",
    descKey: "systemOptimizer.privacy.disableWiFiHotspotsDesc",
    requiresReboot: false,
  },
  {
    id: "disableTypingInsights",
    stateKey: "disableTypingInsights",
    category: "privacy",
    icon: MessageSquare,
    color: COLORS[10],
    enableCmd: "disable_typing_insights",
    disableCmd: "enable_typing_insights",
    titleKey: "systemOptimizer.privacy.disableTypingInsights",
    descKey: "systemOptimizer.privacy.disableTypingInsightsDesc",
    requiresReboot: false,
  },
  {
    id: "disablePreinstalledApps",
    stateKey: "disablePreinstalledApps",
    category: "privacy",
    icon: Download,
    color: COLORS[11],
    enableCmd: "disable_preinstalled_apps",
    disableCmd: "enable_preinstalled_apps",
    titleKey: "systemOptimizer.privacy.disablePreinstalledApps",
    descKey: "systemOptimizer.privacy.disablePreinstalledAppsDesc",
    requiresReboot: false,
  },
  {
    id: "disableDotNetTelemetry",
    stateKey: "disableDotNetTelemetry",
    category: "privacy",
    icon: Code,
    color: COLORS[12],
    enableCmd: "disable_dotnet_telemetry",
    disableCmd: "enable_dotnet_telemetry",
    titleKey: "systemOptimizer.privacy.disableDotNetTelemetry",
    descKey: "systemOptimizer.privacy.disableDotNetTelemetryDesc",
    requiresReboot: false,
  },
  {
    id: "disablePwshTelemetry",
    stateKey: "disablePwshTelemetry",
    category: "privacy",
    icon: Terminal,
    color: COLORS[13],
    enableCmd: "disable_pwsh_telemetry",
    disableCmd: "enable_pwsh_telemetry",
    titleKey: "systemOptimizer.privacy.disablePwshTelemetry",
    descKey: "systemOptimizer.privacy.disablePwshTelemetryDesc",
    requiresReboot: false,
  },
  {
    id: "disableWiFiSense",
    stateKey: "disableWiFiSense",
    category: "privacy",
    icon: Wifi,
    color: COLORS[14],
    enableCmd: "disable_wifi_sense",
    disableCmd: "enable_wifi_sense",
    titleKey: "systemOptimizer.privacy.disableWiFiSense",
    descKey: "systemOptimizer.privacy.disableWiFiSenseDesc",
    requiresReboot: false,
  },
  {
    id: "disableStepRecorder",
    stateKey: "disableStepRecorder",
    category: "privacy",
    icon: Monitor,
    color: COLORS[0],
    enableCmd: "disable_step_recorder",
    disableCmd: "enable_step_recorder",
    titleKey: "systemOptimizer.privacy.disableStepRecorder",
    descKey: "systemOptimizer.privacy.disableStepRecorderDesc",
    requiresReboot: false,
  },

  // ============== 常规应用程序 ==============
  {
    id: "disableOfficeTelemetry",
    stateKey: "disableOfficeTelemetry",
    category: "apps",
    icon: FileText,
    color: COLORS[14],
    enableCmd: "disable_office_telemetry",
    disableCmd: "enable_office_telemetry",
    titleKey: "systemOptimizer.apps.disableOfficeTelemetry",
    descKey: "systemOptimizer.apps.disableOfficeTelemetryDesc",
    requiresReboot: true,
  },
  {
    id: "disableFirefoxTelemetry",
    stateKey: "disableFirefoxTelemetry",
    category: "apps",
    icon: Globe,
    color: COLORS[0],
    enableCmd: "disable_firefox_telemetry",
    disableCmd: "enable_firefox_telemetry",
    titleKey: "systemOptimizer.apps.disableFirefoxTelemetry",
    descKey: "systemOptimizer.apps.disableFirefoxTelemetryDesc",
    requiresReboot: false,
  },
  {
    id: "disableChromeTelemetry",
    stateKey: "disableChromeTelemetry",
    category: "apps",
    icon: Chrome,
    color: COLORS[1],
    enableCmd: "disable_chrome_telemetry",
    disableCmd: "enable_chrome_telemetry",
    titleKey: "systemOptimizer.apps.disableChromeTelemetry",
    descKey: "systemOptimizer.apps.disableChromeTelemetryDesc",
    requiresReboot: false,
  },
  {
    id: "disableNvidiaTelemetry",
    stateKey: "disableNvidiaTelemetry",
    category: "apps",
    icon: Monitor,
    color: COLORS[2],
    enableCmd: "disable_nvidia_telemetry",
    disableCmd: "enable_nvidia_telemetry",
    titleKey: "systemOptimizer.apps.disableNvidiaTelemetry",
    descKey: "systemOptimizer.apps.disableNvidiaTelemetryDesc",
    requiresReboot: true,
  },
  {
    id: "disableVsTelemetry",
    stateKey: "disableVsTelemetry",
    category: "apps",
    icon: Code,
    color: COLORS[3],
    enableCmd: "disable_vs_telemetry",
    disableCmd: "enable_vs_telemetry",
    titleKey: "systemOptimizer.apps.disableVsTelemetry",
    descKey: "systemOptimizer.apps.disableVsTelemetryDesc",
    requiresReboot: false,
  },

  // ============== 触碰 ==============
  {
    id: "disableWindowsInk",
    stateKey: "disableWindowsInk",
    category: "touch",
    icon: Pen,
    color: COLORS[4],
    enableCmd: "disable_windows_ink",
    disableCmd: "enable_windows_ink",
    titleKey: "systemOptimizer.touch.disableWindowsInk",
    descKey: "systemOptimizer.touch.disableWindowsInkDesc",
    requiresReboot: false,
  },
  {
    id: "disableSpellCheck",
    stateKey: "disableSpellCheck",
    category: "touch",
    icon: SpellCheck,
    color: COLORS[5],
    enableCmd: "disable_spelling_typing",
    disableCmd: "enable_spelling_typing",
    titleKey: "systemOptimizer.touch.disableSpellCheck",
    descKey: "systemOptimizer.touch.disableSpellCheckDesc",
    requiresReboot: false,
  },
  {
    id: "disableCloudClipboard",
    stateKey: "disableCloudClipboard",
    category: "touch",
    icon: Clipboard,
    color: COLORS[6],
    enableCmd: "disable_cloud_clipboard",
    disableCmd: "enable_cloud_clipboard",
    titleKey: "systemOptimizer.touch.disableCloudClipboard",
    descKey: "systemOptimizer.touch.disableCloudClipboardDesc",
    requiresReboot: false,
  },

  // ============== 游戏 ==============
  {
    id: "enableGameMode",
    stateKey: "enableGameMode",
    category: "gaming",
    icon: Gamepad2,
    color: COLORS[7],
    enableCmd: "enable_gaming_mode",
    disableCmd: "disable_gaming_mode",
    titleKey: "systemOptimizer.gaming.enableGameMode",
    descKey: "systemOptimizer.gaming.enableGameModeDesc",
    requiresReboot: true,
  },
  {
    id: "disableXboxLive",
    stateKey: "disableXboxLive",
    category: "gaming",
    icon: X,
    color: COLORS[8],
    enableCmd: "disable_xbox_live",
    disableCmd: "enable_xbox_live",
    titleKey: "systemOptimizer.gaming.disableXboxLive",
    descKey: "systemOptimizer.gaming.disableXboxLiveDesc",
    requiresReboot: true,
  },
  {
    id: "disableGameBar",
    stateKey: "disableGameBar",
    category: "gaming",
    icon: Gamepad,
    color: COLORS[9],
    enableCmd: "disable_game_bar",
    disableCmd: "enable_game_bar",
    titleKey: "systemOptimizer.gaming.disableGameBar",
    descKey: "systemOptimizer.gaming.disableGameBarDesc",
    requiresReboot: false,
  },
];

export const categoryLabels: Record<OptimizerCategory, string> = {
  system: "systemOptimizer.category.system",
  disk: "systemOptimizer.category.disk",
  privacy: "systemOptimizer.category.privacy",
  apps: "systemOptimizer.category.apps",
  touch: "systemOptimizer.category.touch",
  gaming: "systemOptimizer.category.gaming",
};

export const categoryOrder: OptimizerCategory[] = [
  "system",
  "disk",
  "privacy",
  "apps",
  "touch",
  "gaming",
];
